### PR TITLE
Wercker box version update to run RethinkDB 1.13

### PR DESCRIPTION
**Pull request by ghost**
I've just [pull requested](https://github.com/mies/box-rethinkdb/pull/1) some changes to the wercker box used for the testing of **gorethink**.

So, as soon as @mies merges the commits it will be possible to run RethinkDB v1.13 and tests on #98 should start passing.

### CODE REVIEW

**Comment by ghost** [comment]
Is there a way to restart Wercker build process?

**Comment by dancannon** [comment]
Not as far as I am aware, however I wouldn't call myself a Wercker expert :P

**Comment by mies** [comment]
You are able to "abort builds" and then rebuild them but not restart a build in general—

**Comment by ghost** [comment]
@dancannon, could you please update it one more time to `mies/rethinkdb@0.1.9`. Or just use `anonx/rethinkdb@0.1.8`. Both versions are similar and running RethinkDB 1.13.

**Comment by dancannon** [comment]
Sure ill do that when I get back home.

**Pull request merged**
