### PR TITLE
Transition to protobuf based protocol v0.3

### PR DESCRIPTION
**Pull request by ghost**
While #95 isn't ready yet shouldn't the driver be moved to protobuf based v0.3? So it's possible to implement `changes()` & `http()` and keep the driver up to date and fully compatible with RethinkDB 1.13.

### CODE REVIEW

**Comment by dancannon** [comment]
Yeah I agree with that decision. It might even be worth getting a v1.13 release out before looking at JSON.

Also thanks for tidying up/fixing the auth key code. I suppose this will also need a test, I have created #99 for this purpose.

**Comment by dancannon** [comment]
I think rerunning all the tests might be overkill. All we need to check is if the driver can connect with an auth key.

**Comment by dancannon** [comment]
Maybe it would be make sense to run something like

```
RETHINKDB_AUTHKEY=test_key go test -test.f="TestConnectAuthKey" -test.v=true
```

**Comment by ghost** [comment]
> I think rerunning all the tests might be overkill

Yes, you're right. I didn't know `-gocheck.f=""` flag exist.

So we just need to implement `func (s *RethinkSuite) TestConnectAuthKey(c *test.C)` similar to [`Example()`](https://github.com/dancannon/gorethink/blob/master/example_test.go#L22) but with `AuthKey` parameter, right?

And in what file should that function be located?

P.S.: Well, this discussion is more related to #99.

**Comment by dancannon** [comment]
I have got started on this now.

I have put it in session_test.go.

**Pull request merged**
